spring:
  application:
    name: @project.artifactId@

  datasource:
    url: jdbc:postgresql://localhost:5432/decks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}