spring:
  application:
    name: @project.artifactId@
  
  cloud:
    gateway:
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/v1/cards/**
            - Path=/api/v1/decks/*/cards
          filters:
            - StripPrefix=2
        - id: deck-service
          uri: lb://deck-service
          predicates:
            - Path=/api/v1/decks/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
  port: 8080